name: PHP Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'

    - name: Install dependencies
      run: composer install

    - name: Run PHPUnit tests
      run: phpunit --configuration sobanbadonia07/Food-Delivery-PHP/php.xml
      working-directory: sobanbadonia07/Food-Delivery-PHP/Testing

