name: CI CD - BuildAndTest

on: 
  push:
  pull_request:


jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.10, 3.11, 3.12]

    name: Run Build
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
    - uses: actions/setup-python@v3
      with: 
        python-version: ${{ matrix.python_version }}

    - name: Install dependencies
    - run: |
        python -m pip install --upgrade pip
        python -m pip install selenium
        python -m pip install pytest

    - name: Run Tests with Selenium
      run: pytest UT11.py





