
name: Enable Automated test run

on: 
  push:
    branches: 
      - 'main'
    pull_request:
      branches:
      - 'main'

jobs:
  automatedtest:
    runs on: ubuntu-latest

    steps:
    - name: First Step
      run: echo Automated tests enabled 
      
